--SELECT * FROM PEREMPMS
SELECT * FROM  SEC_ADMUSR_LOG

SELECT * INTO SECUSERGRP_20230129 FROM SECUSERGRP

UPDATE SECUSERGRP SET USER_GROUP='Admin' where USER_ID='10002'

DELETE from SECUSERGRP WHERE USER_ID='10002'