--无法离职处理

SELECT SUPER_ID, PROCESSED, STAFF_NO, TASK_ID, SEQ FROM fangpuhrm..ATT_OT_PROCESS 
WHERE SUPER_ID = '10015' 
AND PROCESSED = 0    ORDER BY STAFF_NO  ASC, TASK_ID  ASC, SEQ  ASC

SELECT SUPER_ID, PROCESSED, STAFF_NO, TASK_ID, SEQ FROM fangpuhrm..ATT_OT_PROCESS 
WHERE PROCESSED = 0    ORDER BY STAFF_NO  ASC

UPDATE fangpuhrm..ATT_OT_PROCESS  SET PROCESSED=1 WHERE SUPER_ID='10015'