--HRM系统查询工资报表无数据修复
SELECT STAFF_NO, TABLE_NAME, FIELD_NAME, COMPARE_MODE, SRC_VALUE, FIELD_TYPE 
delete FROM fangpuhrm..PAY_REPORT_FORM_QUERY 
WHERE STAFF_NO = '10004'    ORDER BY STAFF_NO  ASC, TABLE_NAME  ASC, FIELD_NAME  ASC, COMPARE_MODE  ASC, SRC_VALUE  ASC

--修复工资计算错误
SELECT * FROM SYS_OPE_LOG WHERE CONTROL_NAME='paycalpro'
