CREATE TABLE t_DF24RealTimeDataLogger(
	fNumericID INT,
	fPowerOnState INT,
	fQuality INT,
	fTimestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	fFurnaceState INT,
	fLiterState INT,
	fDemouldingState INT,
	fAlarmState INT,
	fProductID BIGINT,
	fICMONo BIGINT,
	fStaffNo BIGINT,
	fStandardOut INT,
	fActualOut NUMERIC,
	fEfficiency NUMERIC
)

SELECT create_hypertable('t_DF11RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF12RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF13RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF14RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF15RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF16RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF17RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF18RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF19RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF20RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF21RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF22RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF23RealTimeDataLogger','ftimestamp');
SELECT create_hypertable('t_DF24RealTimeDataLogger','ftimestamp');

SELECT * FROM t_DF01RealTimeDataLogger


CREATE TABLE t_DF20ProductInfoLogger(
	fID INTEGER GENERATED BY DEFAULT AS IDENTITY,
	fNumericID INTEGER,
	fValue INTEGER,
	fQuality INTEGER,
	fTimestamp TIMESTAMP WITH TIME ZONE NOT NULL,
	fProductID INTEGER,
	fWeight NUMERIC,
	fOvenMaterialTemperature NUMERIC,
	fOvenMoldTemperature_1 NUMERIC,
	fOvenMoldTemperature_2 NUMERIC,
	fSerialNumber BIGINT
);
SELECT create_hypertable('t_DF20ProductInfoLogger','ftimestamp');


SELECT * FROM t_DF20ProductInfoLogger