select FName,* from t_Emp

sp_help t_Emp
update t_Emp set F_102='10001' where right(FName,len(FName)-1)='' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'


select case when left(FName,1) like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
				then right(FName,len(FName)-1)
			when left(FName,2) like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
				then right(FName,len(FName)-2)
			else
				FName
			end
from t_Emp
where FName like '%Àæª˙%'

update t_Emp set F_102=' ' where right(FName,len(FName)-1)=''
select F_102,FName from t_Emp where F_102 IS NULL

update t_Emp set F_102='10001' where right(FName,len(FName)-1)='∑ΩÀ…œ≤ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10002' where right(FName,len(FName)-1)='ª∆π¿º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10003' where right(FName,len(FName)-1)='∏ﬂÕÒÊ√ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10004' where right(FName,len(FName)-1)='¿Ó¥‰”® ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10005' where right(FName,len(FName)-1)='∑∂÷•±Ã ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10006' where right(FName,len(FName)-1)='÷‹”æ…∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10007' where right(FName,len(FName)-1)='Õı¥Ô»› ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10008' where right(FName,len(FName)-1)='¬Ì”Ò¡· ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10009' where right(FName,len(FName)-1)='Œƒ◊Í’‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10010' where right(FName,len(FName)-1)='≥¬»˝”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10011' where right(FName,len(FName)-1)='≥¬¿ˆÊ√ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10012' where right(FName,len(FName)-1)='ª∆–”«Ô ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10013' where right(FName,len(FName)-1)='Œ¬Ωı¡™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10014' where right(FName,len(FName)-1)='¡∫»”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10015' where right(FName,len(FName)-1)='¬∑—ÔÊº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10016' where right(FName,len(FName)-1)='∫Œ—ﬁ¡· ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10017' where right(FName,len(FName)-1)='ª∆√Ù”® ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10018' where right(FName,len(FName)-1)='ÀÔÁ≤Ê√ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10019' where right(FName,len(FName)-1)='—œΩ‹ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10020' where right(FName,len(FName)-1)='Õı±Û ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10021' where right(FName,len(FName)-1)='∫ŒΩ‹–≈ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10022' where right(FName,len(FName)-1)='≤Ã ˜»∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10023' where right(FName,len(FName)-1)='¥˜Á¯ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10024' where right(FName,len(FName)-1)='≈∑√Ù“« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10025' where right(FName,len(FName)-1)='Ã∑æ≤ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10026' where right(FName,len(FName)-1)='¬ΩΩ‹”¿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10027' where right(FName,len(FName)-1)='¿ÓºÛ≤≈ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10028' where right(FName,len(FName)-1)='∂≠”–¥∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10029' where right(FName,len(FName)-1)='Ã∑–¢÷“ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10030' where right(FName,len(FName)-1)='µÀ¿˚∫Í ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10031' where right(FName,len(FName)-1)='∂≠»˝Œ¿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10032' where right(FName,len(FName)-1)='Œ‚÷æº· ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10033' where right(FName,len(FName)-1)='¬Û¿ˆœº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10034' where right(FName,len(FName)-1)='∑∂∫ËŒƒ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10035' where right(FName,len(FName)-1)='÷£œ˛¥ø ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10036' where right(FName,len(FName)-1)='√´√Òœ„ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10037' where right(FName,len(FName)-1)='µÀΩ£∆º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10038' where right(FName,len(FName)-1)='≥¬œ˛¡÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10039' where right(FName,len(FName)-1)='¡ıªÔ¿º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10040' where right(FName,len(FName)-1)='œÁŒ∞±Ú ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10041' where right(FName,len(FName)-1)='Î¯π˙»Ÿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10042' where right(FName,len(FName)-1)='ÀÔ–°∆º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10043' where right(FName,len(FName)-1)='»›…Ÿ—‡ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10044' where right(FName,len(FName)-1)='≈Àπ„≥– ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10045' where right(FName,len(FName)-1)='ª∆Ωı–« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10046' where right(FName,len(FName)-1)='Ã∑ø≠–˝ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10047' where right(FName,len(FName)-1)='Á—∑Í¥∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10048' where right(FName,len(FName)-1)='¡∫“ÿ»´ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10049' where right(FName,len(FName)-1)='ª∆—ﬁ∫Ï ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10050' where right(FName,len(FName)-1)='¡ıÊœæÍ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10051' where right(FName,len(FName)-1)='≥¬πœº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10052' where right(FName,len(FName)-1)='∫Œ»Ò«⁄ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10053' where right(FName,len(FName)-1)='÷Ï√˜œº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10054' where right(FName,len(FName)-1)='—Óº—¥ø ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10055' where right(FName,len(FName)-1)='—Ó¥∫‘£ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10056' where right(FName,len(FName)-1)='∑Î Á“À ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10057' where right(FName,len(FName)-1)='÷ÏΩı√∑ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10058' where right(FName,len(FName)-1)='¡÷æ≤“« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10059' where right(FName,len(FName)-1)='¬ﬁ≈ÂÊ√ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10060' where right(FName,len(FName)-1)='≥¬ÏÃΩ‹ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10061' where right(FName,len(FName)-1)='¡∫¡¯–¿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10062' where right(FName,len(FName)-1)='Ã∑ª›«ø ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10063' where right(FName,len(FName)-1)='¡∫±¶“« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10064' where right(FName,len(FName)-1)='–§Ω®±Û ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10065' where right(FName,len(FName)-1)='À’Ω≠¡÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10066' where right(FName,len(FName)-1)='¡ı»ÀŒı ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10067' where right(FName,len(FName)-1)='Œ‚∑Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10068' where right(FName,len(FName)-1)='¿ËΩı∫¿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10069' where right(FName,len(FName)-1)='ÀÔœ≤«Ï ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10070' where right(FName,len(FName)-1)='≥¬–°¿ˆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10071' where right(FName,len(FName)-1)='¡ı¬˙«Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10072' where right(FName,len(FName)-1)='¡∫Ω‹ § ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10073' where right(FName,len(FName)-1)='∫´ºŒ…˘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10074' where right(FName,len(FName)-1)='≤‹¿Ú ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10075' where right(FName,len(FName)-1)='–Ìæ≤¿º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10076' where right(FName,len(FName)-1)='π˘’Ò≈Ù ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10077' where right(FName,len(FName)-1)='¡∫÷–»™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10078' where right(FName,len(FName)-1)='À’æ¥∫È ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10079' where right(FName,len(FName)-1)='≤‹√Ø ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10080' where right(FName,len(FName)-1)='’≈—ß«⁄ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10081' where right(FName,len(FName)-1)='¡ı÷æŒ∞ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10082' where right(FName,len(FName)-1)='Ã∑”¿Ωı ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10083' where right(FName,len(FName)-1)='÷‹—µ≤≈ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10084' where right(FName,len(FName)-1)='∫Œ”¿∫∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10085' where right(FName,len(FName)-1)='Õı÷æ∆Ω ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10086' where right(FName,len(FName)-1)='»ƒ…‹…˙ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10087' where right(FName,len(FName)-1)='≥¬‘À…Ó ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10088' where right(FName,len(FName)-1)='ŒÈ√˜∫Ï ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10089' where right(FName,len(FName)-1)='‘¯ΩÀ… ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10090' where right(FName,len(FName)-1)='∏ —◊Œƒ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10091' where right(FName,len(FName)-1)='≥¬≤® ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10092' where right(FName,len(FName)-1)='∏∂À≥“Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10093' where right(FName,len(FName)-1)='”Ò√Õ»™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10094' where right(FName,len(FName)-1)='ª∆π˙Ω´ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10095' where right(FName,len(FName)-1)='’≈πßΩ≠ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10096' where right(FName,len(FName)-1)='¬ﬁ¥∫ª™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10097' where right(FName,len(FName)-1)='¬ﬁ‘®Ïı ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10098' where right(FName,len(FName)-1)='’≈◊”∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10099' where right(FName,len(FName)-1)='’≈∫£–€ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10100' where right(FName,len(FName)-1)='¡∫≥˛ÃÔ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10101' where right(FName,len(FName)-1)='ª∆π˙Ω‹ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10102' where right(FName,len(FName)-1)='“∂◊˜Ω£ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10103' where right(FName,len(FName)-1)='π˘◊‘±Û ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10104' where right(FName,len(FName)-1)='¿ÓÜ¢ª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10105' where right(FName,len(FName)-1)='≈∑¿˚∆Ω ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10106' where right(FName,len(FName)-1)='“¶ø°‘∆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10107' where right(FName,len(FName)-1)='¬ﬁº“Õ˙ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10108' where right(FName,len(FName)-1)='’≈‘∫ª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10109' where right(FName,len(FName)-1)='”Ò“Â»™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10110' where right(FName,len(FName)-1)='¡ıÕ˚ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10111' where right(FName,len(FName)-1)='ª∆π¡÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10112' where right(FName,len(FName)-1)='÷Ïæ’œ„ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10113' where right(FName,len(FName)-1)='¡∫¬Ω÷˝ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10114' where right(FName,len(FName)-1)='ª∆π‘∆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10115' where right(FName,len(FName)-1)='÷Ï”¶’‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10116' where right(FName,len(FName)-1)='—œÕ˛±Ú ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10117' where right(FName,len(FName)-1)='’≈πß’˛ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10118' where right(FName,len(FName)-1)='–§Ω£∑Ê ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10119' where right(FName,len(FName)-1)='Ω≠“Â∫£ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10120' where right(FName,len(FName)-1)='¬¿∫Á∏÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10121' where right(FName,len(FName)-1)='¡ıÀ… ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10122' where right(FName,len(FName)-1)='À’Ã⁄”– ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10123' where right(FName,len(FName)-1)='—œº·∑… ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10124' where right(FName,len(FName)-1)='Ã∑Œƒª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10125' where right(FName,len(FName)-1)='¡Ë∫∆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10126' where right(FName,len(FName)-1)='¡Ë÷« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10127' where right(FName,len(FName)-1)='∫˙∞¢ƒ› ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10128' where right(FName,len(FName)-1)='÷Ï«‡«‡ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10129' where right(FName,len(FName)-1)='Ω“–°æÍ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10130' where right(FName,len(FName)-1)='Œ§Õ≥±Û ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10131' where right(FName,len(FName)-1)='÷‹∑Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10132' where right(FName,len(FName)-1)='µÀπ˙–„ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10133' where right(FName,len(FName)-1)='Ω“πÛ√˜ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10134' where right(FName,len(FName)-1)='÷ÏπÃ“ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10135' where right(FName,len(FName)-1)='Œ§Õ≥Ω‹ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10136' where right(FName,len(FName)-1)='’≈πß’˚ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10137' where right(FName,len(FName)-1)='¿Ó…œ≈Œ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10138' where right(FName,len(FName)-1)='¿Ó√¿”Ò ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10139' where right(FName,len(FName)-1)='≥¬–¢∆Ω ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10140' where right(FName,len(FName)-1)='ªÙπ„’Ú ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10141' where right(FName,len(FName)-1)='’≈∞ÿ±Û ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10142' where right(FName,len(FName)-1)='–ª–°ª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10143' where right(FName,len(FName)-1)='¬∑–°æ’ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10144' where right(FName,len(FName)-1)='ª∆¥∫œ˛ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10145' where right(FName,len(FName)-1)='≥¬◊””˝ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10146' where right(FName,len(FName)-1)='Œ§÷‹Õ£ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10147' where right(FName,len(FName)-1)='Õı¡÷∑“ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10148' where right(FName,len(FName)-1)='’≈Ã´±Ã ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10149' where right(FName,len(FName)-1)='Œ‚–°∫Ï ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10150' where right(FName,len(FName)-1)='¡ıΩ®”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10151' where right(FName,len(FName)-1)='Õı»Â¥∫ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10152' where right(FName,len(FName)-1)='¿Ó»∫ª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10153' where right(FName,len(FName)-1)='ø◊»∫”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10154' where right(FName,len(FName)-1)='¡∫¡¨œº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10155' where right(FName,len(FName)-1)='∏ »’√√ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10156' where right(FName,len(FName)-1)='ÕÙ∂®¥‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10157' where right(FName,len(FName)-1)='≥¬¿ˆ∆º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10158' where right(FName,len(FName)-1)='¿Ó‘  ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10159' where right(FName,len(FName)-1)='¡ı’◊‘∆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10160' where right(FName,len(FName)-1)='À’Ωø∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10161' where right(FName,len(FName)-1)='«ÀÆ∆Ω ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10162' where right(FName,len(FName)-1)='≥…∫£”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10163' where right(FName,len(FName)-1)='‘¯¡÷”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10164' where right(FName,len(FName)-1)='≥¬¡¨∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10165' where right(FName,len(FName)-1)='—Óµ¬¿º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10166' where right(FName,len(FName)-1)='∏∂—ﬁ√∑ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10167' where right(FName,len(FName)-1)='¡Œ√Á√Á ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10168' where right(FName,len(FName)-1)='¡ıøÀÀ´ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10169' where right(FName,len(FName)-1)='∏µ–°«€ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10170' where right(FName,len(FName)-1)='¬≥“Ê¡¥ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10171' where right(FName,len(FName)-1)='¿Ó∫Ï—‡ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10172' where right(FName,len(FName)-1)='¡ı–À±Ã ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10173' where right(FName,len(FName)-1)='◊Û È”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10174' where right(FName,len(FName)-1)='≥¬—‡ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10175' where right(FName,len(FName)-1)='≥¬‘¬√ƒ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10176' where right(FName,len(FName)-1)='¡ı“¯«Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10177' where right(FName,len(FName)-1)='∫´“‡√º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10178' where right(FName,len(FName)-1)='¿÷…Ÿ«Ÿ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10179' where right(FName,len(FName)-1)='¬ﬁ∆Ωœº ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10180' where right(FName,len(FName)-1)='¿µ≈Ê∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10181' where right(FName,len(FName)-1)='¡ıøÀ¥‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10182' where right(FName,len(FName)-1)='≥¬∑Ô”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10183' where right(FName,len(FName)-1)='–‹÷–¬∂ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10184' where right(FName,len(FName)-1)='÷‹«Â’‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10185' where right(FName,len(FName)-1)='¿Ó ˆ√∑ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10186' where right(FName,len(FName)-1)='Œ‚≤® ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10187' where right(FName,len(FName)-1)='À’«Ô¿º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10188' where right(FName,len(FName)-1)='Õı≥…∫Ï ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10189' where right(FName,len(FName)-1)='”Ò∑º∆º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10190' where right(FName,len(FName)-1)='÷”¥‰”¢ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10191' where right(FName,len(FName)-1)='’≈Ë¥ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10192' where right(FName,len(FName)-1)='ª∆«Ô‘∆ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10193' where right(FName,len(FName)-1)='≥¬…Ÿ√ƒ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10194' where right(FName,len(FName)-1)='¡ı”∞ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10195' where right(FName,len(FName)-1)='≥¬…≥…≥ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10196' where right(FName,len(FName)-1)='ÕÙ∂®∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10197' where right(FName,len(FName)-1)='œƒ”Í ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10198' where right(FName,len(FName)-1)='’≈Ω®ª™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10199' where right(FName,len(FName)-1)='Ω≠–¬ƒ‹ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10200' where right(FName,len(FName)-1)='Œ◊∏£Ãœ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10201' where right(FName,len(FName)-1)='Ã∑œÎœÎ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10202' where right(FName,len(FName)-1)='¡ı÷“∑® ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10203' where right(FName,len(FName)-1)='Œ‚–°±Ã ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10204' where right(FName,len(FName)-1)='ª∆±¶∏˝ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10205' where right(FName,len(FName)-1)='”‡∏’ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10206' where right(FName,len(FName)-1)='≥¬∫£ª‘ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10207' where right(FName,len(FName)-1)='’≈∂≠∑Ô ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10208' where right(FName,len(FName)-1)='À’ª™Œ‰ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10209' where right(FName,len(FName)-1)='∫Œ∑…¡˙ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10210' where right(FName,len(FName)-1)='¬ﬁŒ∞√˜ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10211' where right(FName,len(FName)-1)='ø◊π˙ª™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10212' where right(FName,len(FName)-1)='‘¨µ¬¡÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10213' where right(FName,len(FName)-1)='∑ΩÀ…µ¬ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10214' where right(FName,len(FName)-1)='‹˜∆Ù√Ò ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10215' where right(FName,len(FName)-1)='≤‹««æ¸ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10216' where right(FName,len(FName)-1)='ŒÈ¥‘π˙ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10217' where right(FName,len(FName)-1)='÷ÏΩ› ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10218' where right(FName,len(FName)-1)='¡ıƒœ–« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10219' where right(FName,len(FName)-1)='ª∆∫œ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10220' where right(FName,len(FName)-1)='⁄˘…≠À… ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10221' where right(FName,len(FName)-1)='¡ıµ˜–Ω ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10222' where right(FName,len(FName)-1)='’≈Ω£Õ¶ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10223' where right(FName,len(FName)-1)='Ã∑ª™«Â ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10224' where right(FName,len(FName)-1)='¿Ó÷æª™ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10225' where right(FName,len(FName)-1)='’≈◊ÍŒ∞ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10226' where right(FName,len(FName)-1)='¡∫‘À¡÷ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10227' where right(FName,len(FName)-1)='Ã∆”—√˜ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10228' where right(FName,len(FName)-1)='⁄˘»Ò∑º ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10229' where right(FName,len(FName)-1)='–Ìœ‡º« ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10230' where right(FName,len(FName)-1)='º÷µ«Œƒ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10231' where right(FName,len(FName)-1)='Œ§π‚∫œ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10232' where right(FName,len(FName)-1)='¬ﬁ—‡√˜ ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10233' where right(FName,len(FName)-1)='≤‹—«œË ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10234' where right(FName,len(FName)-1)='‘¯‘£∑· ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10235' where right(FName,len(FName)-1)='√…”¬Ï” ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10236' where right(FName,len(FName)-1)='—Ó–˜∑Ê ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
update t_Emp set F_102='10237' where right(FName,len(FName)-1)='—¶≈  ' and  left(FName,1) COLLATE Chinese_PRC_CS_AS  like '%[ABCDEFGHIJKLMNOPQRSTUVWXYZ]%'
