DBCC SQLPERF(LOGSPACE)


SELECT name 
,size/128.0 as size_MB
,size/128.0 - CAST(FILEPROPERTY(name, 'SpaceUsed') AS int)/128.0 AS AvailableSpaceInMB
,*
FROM sys.database_files;


USE [tempdb]
GO
DBCC FREESYSTEMCACHE ('ALL')
GO
DBCC SHRINKFILE(N'tempdev',2)
DBCC SHRINKFILE(N'templog',2)
DBCC SHRINKFILE(N'temp2',2)
DBCC SHRINKFILE(N'temp3',2)
DBCC SHRINKFILE(N'temp4',2)
DBCC SHRINKFILE(N'temp5',2)
DBCC SHRINKFILE(N'temp6',2)
DBCC SHRINKFILE(N'temp7',2)
DBCC SHRINKFILE(N'temp8',2)
GO

USE [TEMPDB]
GO
DBCC SHRINKFILE(N'tempdev.mdf',0,TRUNCATEONLY)
GO

ALTER DATABASE AIS20140921170539 SET RECOVERY SIMPLE;
GO

CHECKPOINT;
GO

DBCC SHRINKFILE ('SCM102SP2_log', 10);
GO

ALTER DATABASE AIS20140921170539 SET RECOVERY FULL;
GO

DBCC LOGINFO;


DBCC OPENTRAN

SELECT session_id, elapsed_time_seconds
FROM sys.dm_tran_active_snapshot_database_transactions