SELECT COUNT(*) FROM ICMO
UNION ALL
SELECT COUNT(*) FROM ICShop_FlowCard
UNION ALL
SELECT COUNT(*) FROM ICShop_FlowCardEntry
UNION ALL
SELECT COUNT(*) FROM SEOrder
UNION ALL
SELECT COUNT(*) FROM SEOrderEntry
UNION ALL
SELECT COUNT(*) FROM SHProcRpt
UNION ALL
SELECT COUNT(*) FROM SHProcRptMain
UNION ALL
SELECT COUNT(*) FROM t_Emp
UNION ALL
SELECT COUNT(*) FROM ICStockBill
UNION ALL
SELECT COUNT(*) FROM ICStockBillEntry
UNION ALL
SELECT COUNT(*) FROM t_Item
UNION ALL
SELECT COUNT(*) FROM t_ICItemBase
UNION ALL
SELECT COUNT(*) FROM t_ICItemCore
UNION ALL
SELECT COUNT(*) FROM t_Barcode
UNION ALL
SELECT COUNT(*) FROM t_BASE_ICItemEntrance
UNION ALL
SELECT COUNT(*) FROM t_ICItemCustom
UNION ALL
SELECT COUNT(*) FROM t_ICItemDesign
UNION ALL
SELECT COUNT(*) FROM t_ICItemMaterial
UNION ALL
SELECT COUNT(*) FROM t_ICItemPlan
UNION ALL
SELECT COUNT(*) FROM t_ICItemQuality
UNION ALL
SELECT COUNT(*) FROM t_ICItemStandard
UNION ALL
SELECT COUNT(*) FROM ICInventory
UNION ALL
SELECT COUNT(*) FROM t_Submessage
UNION ALL
SELECT COUNT(*) FROM t_Resource    